# Generated by Django 4.1.3 on 2024-08-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VETTORRES', '0002_customuser_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='whatsapp_number',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
