# Generated by Django 4.1.3 on 2024-08-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VETTORRES', '0003_alter_customuser_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
