# Generated by Django 4.1.3 on 2024-08-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VETTORRES', '0004_alter_customuser_whatsapp_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='cancelada',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='whatsapp_number',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
