# Generated by Django 4.1.3 on 2024-09-01 17:33

from django.db import migrations

def create_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('VETTORRES', 'UserProfile')
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('VETTORRES', '0006_remove_customuser_whatsapp_number_userprofile'),
    ]

    operations = [
         migrations.RunPython(create_profiles),
    ]
