# Generated by Django 4.1.3 on 2024-09-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VETTORRES', '0007_create_user_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cita',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
