# Generated by Django 4.1.3 on 2024-09-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VETTORRES', '0010_remove_userprofile_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
