# Generated by Django 4.1.3 on 2024-09-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VETTORRES', '0011_comentario_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
