# Generated by Django 4.1.3 on 2024-09-06 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('VETTORRES', '0012_contacto_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='fecha_fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
